name: Pull Request Workflow

on: [pull_request]

jobs:
  pull-request-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - name: Set up Java
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: 16

      - name: Clean code
        run: |
          mvn clean

      - name: Validating code
        run: |
          mvn validate

      - name: Compiling code
        run: |
          mvn compile

      - name: Testing code
        run: |
          mvn test

      - name: Packaging code
        run: |
          mvn package

      - name: Verifying code
        run: |
          mvn verify

      - run: echo "ğŸ This job's status is ${{ job.status }}."
